# Generated by Django 6.0.3 on 2026-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor_id',
            field=models.CharField(default='n/a', max_length=20),
        ),
    ]
