# Generated by Django 6.0.3 on 2026-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emerygency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emerygency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
