# Generated by Django 6.0.3 on 2026-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='n/a', max_length=15),
        ),
    ]
