# Generated by Django 6.0.3 on 2026-03-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sstatus',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
