# Generated by Django 6.0.3 on 2026-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment_sstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sstatus',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('RE', 'Re')], default='No', max_length=3),
        ),
    ]
