# Generated by Django 6.0.3 on 2026-03-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_emerygency_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emerygency_contact_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emerygency_contact_phone',
            new_name='emergency_contact_phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
