# Generated by Django 6.0.3 on 2026-03-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_rating_patient_id_rating_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.appointment'),
            preserve_default=False,
        ),
    ]
