# Generated by Django 6.0.3 on 2026-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
