# Generated by Django 6.0.3 on 2026-03-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_emerygency_contact_name_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
    ]
