# Generated by Django 6.0.3 on 2026-03-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_consultation_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='patient',
        ),
        migrations.AddField(
            model_name='rating',
            name='consultation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.appointment'),
        ),
        migrations.AddField(
            model_name='rating',
            name='patient_id',
            field=models.CharField(default='unknown_patient', max_length=20),
            preserve_default=False,
        ),
    ]
