# Generated by Django 6.0.3 on 2026-03-21 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionist',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', 'On Duty'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=10),
        ),
    ]
