# Generated by Django 6.0.3 on 2026-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
