# Generated by Django 6.0.3 on 2026-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patient_created_at_receptionist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', 'On Duty'), ('ON_LEAVE', 'On Leave')], default='ON_DUTY', max_length=10),
        ),
    ]
