# Generated by Django 6.0.3 on 2026-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_receptionist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='Receptionist_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], default='MORNING', max_length=10),
        ),
    ]
