# Generated by Django 6.0.3 on 2026-03-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
