# Generated by Django 6.0.3 on 2026-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_receptionist_receptionist_id_receptionist_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='status',
            field=models.CharField(choices=[('ON_DUTY', 'On Duty'), ('ON_LEAVE', 'On Leave'), ('OFF_DUTY', 'Off Duty')], default='ON_DUTY', max_length=10),
        ),
    ]
